function [k_global,f_global,g_global] = ...
            assemble_nl(mesh,el,k_global,k_el,g_global,g_el,f_global,f_gamma_el,f_omega_el)
gi = mesh(el).global_indices;
indices = [gi*2-1; gi*2];
indices = reshape(indices,[1,numel(indices)]);
k_global(indices,indices) = ...
    k_global(indices,indices) + ...
    k_el;
f_global(indices) = ...
    f_global(indices) + f_gamma_el + f_omega_el;
g_global(indices) = g_global(indices) + g_el;
end